syms w nu mu
alpha = 1 + 2*mu+3*nu;
beta = -mu-2*nu;
gamma = 2*mu;
delta = -2-4*nu;
sigma = nu/2;

und_sqrt = (beta^2 - 4*sigma*(alpha-2*sigma)) * w^4 ...
    +(2*beta*gamma - 4*delta*sigma) * w^3 ...
    +(2*beta^2+gamma^2 - 8*sigma*(alpha - 2*sigma)) * w^2 ...
    +(2*beta*gamma - 4*delta*sigma) * w ...
    +(beta^2 - 4*sigma*(alpha-2*sigma));
eta_1 = 1/(2*sigma*(1+w^2)) * ...
    (-beta*(1+w^2) - gamma*w * sqrt(und_sqrt));
eta_2 = 1/(2*sigma*(1+w^2)) * ...
    (-beta*(1+w^2) + gamma*w * sqrt(und_sqrt));

eps_und_sqrt = (2*beta*gamma - 4*delta*sigma)^2 ...
    -4*gamma^2 * (beta^2 - 4*sigma*(alpha-2*sigma));
eps_1 = 1/(beta^2 - 4*sigma*(alpha-2*sigma)) ...
    * (-beta*gamma + 2*delta*sigma ...
    -.5 * sqrt(eps_und_sqrt));
eps_2 = 1/(beta^2 - 4*sigma*(alpha-2*sigma)) ...
    * (-beta*gamma + 2*delta*sigma ...
    +.5 * sqrt(eps_und_sqrt));